version: '3.7'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    
    links:
      - neo4j

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password